--Requiere modulos
PlayerModule = require("src.libs.player")
EnemyModule = require("src.libs.enemy")
ColliderModule = require("src.libs.collisions")
GunModule = require("src.guns.dev")
Gun = GunModule.new()
Timer = require("src.libs.timer")
UDim2 = require("src.guis.udim2")
Guis = require("src.guis.gui")
Button = require("src.guis.button")
Textlabel = require("src.guis.textlabel")
Frame = require("src.guis.frame")
ImageLabel = require("src.guis.imagelabel")
Config = require("src.utils.config_manager")
Camera = require("src.libs.camera")