name: Build Docs
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Lua and LuaRocks
        uses: leafo/gh-actions-luarocks@v4
      
      - name: Install LDoc
        run: luarocks install ldoc

      - name: Build documentation
        run: ldoc -c config.ld .

      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}